languageCode = "en-us"
title = "SD"
copyright = "Shaun Donachy"
baseURL = "http://notlocalhost/" #
theme = "dopetrope"
enableRobotsTXT = true

[params.projects]
    title = "Projects"
    foldername = "projects"
    findoutmoretext = "Check it out"

[params.blog]
    title = "Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.gallery]
    title = "Gallery"
    foldername = "gallery"
    findoutmoretext = "Check it out"

[params.settings]
    googleanalytics = ""

[params.highlight]
    style = "railscasts"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
